// Disable Tags: soldOut, notAvaliable

export const siteConfig = {
  title: "Course Catalog",
  subtitle: "A list of all STEM courses offered for students in grades K-12",
  scheduleImages: {
    "jan-april": {
      height: 200,
      width: 600,
      alt: "Winter Course Schedule Overview",
      src: "/gallery/placeholder.webp"
    },
    holiday: {
      height: 200,
      width: 600,
      alt: "Holiday Camp Schedule Overview",
      src: "/gallery/placeholder.webp"
    },
    fall: {
      height: 200,
      width: 600,
      alt: "Fall Course Schedule Overview",
      src: "/gallery/placeholder.webp"
    },
    summer: {
      height: 200,
      width: 600,
      alt: "Summer Program Schedule Overview",
      src: "/gallery/placeholder.webp"
    },
  },
}

export const janAprilConfig = {
  title: "2025 Winter Classes",
  description: "13 sessions from January 6 - April 13, 2025. Various STEM disciplines for Grades K-12.",
  classDates: {
    title: "Winter 2025 Class Dates:",
    schedule: {
      Tuesday: "Jan 7, 14, 21, 28 / Feb 4, 11, 18, 25 / Mar 4, 11, 18, 25 / Apr 1, 8",
      Thursday: "Jan 9, 16, 23, 30 / Feb 6, 13, 20, 27 / Mar 6, 13, 20, 27 / Apr 3, 10",
      Friday: "Jan 10, 17, 24, 31 / Feb 7, 14, 21, 28 / Mar 7, 14, 21, 28 / Apr 4, 11",
      Saturday: "Jan 11, 18, 25 / Feb 1, 8, 15, 22 / Mar 1, 8, 15, 22, 29 / Apr 5, 12",
      Sunday: "Jan 12, 19 / Feb 2, 9, 16 / Mar 2, 23, 30 / Apr 6, 13, 20",
    },
  },
}

export const holidayConfig = {
  title: "Holiday Camps",
  description:
    "Join us this holiday season for an immersive robotics and STEM experience. Campers will build and program their own robot, and create a custom holiday gift. All classes will be in-person in Bayside.",
  availableSessions: {
    title: "Available Sessions:",
    sessions: [
      "Session 1: Dec 26-28",
      "Session 2: Dec 30, Jan 2-3",
      "Session 3: February 20-22",
      "Session 4: April 17-19 or 18-20",
    ],
  },
}

export const fallConfig = {
  title: "2025 Fall Classes",
  description:
    "Weekly robotics classes with 10 sessions per class. Introductory VEX IQ and VEX robotics courses for different grade levels.",
  classDates: {
    title: "Fall 2025 Class Dates:",
    schedule: {
      Tuesday: "Sep 9, 16, 23, 30 / Oct 7, 14, 21, 28 / Nov 4, 18",
      Thursday: "Sep 11, 18, 25 / Oct 2, 9, 16, 23, 30 / Nov 6, 13, 20",
      Friday: "Sep 12, 19, 26 / Oct 3, 10, 17, 24 / Nov 7, 14, 21",
      Saturday: "Sep 13, 20, 27 / Oct 4, 11, 18, 25 / Nov 8, 15, 22",
      Sunday: "Sep 14, 21, 28 / Oct 5, 12, 19, 26 / Nov 9, 16, 23",
    },
  },
}

export const summerConfig = {
  title: "2025 Summer Programs",
  description: "Bootcamps, STEM camps, and weekend workshops covering robotics, electronics, and more.",
}

export const janAprilCourses = [
  {
    title: "RM001 - Robotics for Grades K-5",
    description: "Introductory VEX IQ robotics for beginners with project-based learning.",
    gradeLevel: "K - 5th Grade",
    dates: "Jan 6 - Apr 13, 2025",
    time: "Green - Tue/Thu/Sun",
    category: "Beginner Robotics",

    tags: ["robotics", "beginner", "vex-iq"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["VEX IQ basics", "Robot construction", "Simple programming", "Problem-solving"],
    projects: ["Moving robot", "Sensor robot", "Autonomous robot", "Creative designs"],
  },
  {
    title: "RM002 - Robotics for Grades 5-8",
    description: "Intermediate VEX IQ robotics with advanced construction and programming.",
    gradeLevel: "5th - 8th Grade",
    dates: "Jan 6 - Apr 13, 2025",
    time: "Blue - Thursday only",
    category: "Intermediate Robotics",
    tags: ["robotics", "intermediate", "vex-iq"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Advanced VEX IQ", "Programming logic", "Sensor integration", "Design thinking"],
    projects: ["Multi-sensor robot", "Navigation robot", "Competition challenges", "Custom mechanisms"],
  },
  {
    title: "RV001 - Robotics for Grades 6-12",
    description: "VEX robotics covering gear ratios, torque, speed, and mechanical concepts.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2025",
    time: "Red - Sunday only",
    category: "Advanced Robotics",
    tags: ["robotics", "advanced", "vex", "competition"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque calculations", "Programming"],
    projects: ["Competition robot", "Gear demonstrations", "Speed tests", "Custom subsystems"],
  },
  {
    title: "Battlebots 101",
    description: "Design and build battle bots from scratch with CAD and electronics.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2025",
    time: "Yellow - Friday only",
    category: "Engineering Design",
    tags: ["engineering", "design", "cad", "electronics"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Combat design", "CAD modeling", "Electronics", "Manufacturing"],
    projects: ["CAD design", "Control system", "Weapon prototypes", "Final construction"],
  },
  {
    title: "CTC001 - Programming for Grades K-5",
    description: "Learn programming fundamentals, data types, and C++ basics.",
    gradeLevel: "K - 5th Grade",
    dates: "Jan 6 - Apr 13, 2025",
    time: "Grey - Friday only",
    category: "Programming",
    tags: ["programming", "beginner", "cpp"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Programming logic", "Data types", "C++ basics", "Problem solving"],
    projects: ["Calculator", "Story games", "Animations", "Logic puzzles"],
  },
  {
    title: "CPP002 - Programming for Grades 6-12",
    description: "Advanced programming with complex data types, loops, and I/O operations.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2025",
    time: "Orange - Friday only",
    category: "Advanced Programming",
    tags: ["programming", "advanced", "cpp"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Complex data types", "Loops", "I/O operations", "Functions"],
    projects: ["Data management", "Game development", "File processing", "Algorithms"],
  },
  {
    title: "CPP003 - Programming for Grades 6-12",
    description: "Continuation of CPP002 with advanced concepts and data structures.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2025",
    time: "Orange - Saturday only",
    category: "Advanced Programming",
    tags: ["programming", "advanced", "cpp", "data-structures"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Data structures", "OOP", "Algorithms", "Software architecture"],
    projects: ["OOP applications", "Algorithm implementations", "Multi-file programs", "Capstone project"],
  },
  {
    title: "3D Modelling and Design",
    description: "Learn 3D modeling, additive/negative manufacturing, and design principles.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jan 6 - Apr 13, 2025",
    time: "Purple - Thu/Sun",
    category: "Engineering Design",
    tags: ["design", "3d-modeling", "manufacturing"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["3D modeling", "Design principles", "Manufacturing", "Materials"],
    projects: ["3D printed designs", "Mechanical parts", "Artistic models", "Prototypes"],
  },
]

export const holidayCourses = [
  {
    title: "Holiday Camp - Grades K-5 (Half Days)",
    description: "Design, build and program your own robot in this immersive 3-day experience.",
    gradeLevel: "K - 5th Grade",
    dates: "Multiple sessions available",
    time: "Morning 9am-12pm OR Afternoon 1pm-4pm",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "beginner", "half-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Robot design", "Basic programming", "Problem solving", "Creative thinking"],
    projects: ["Custom robot build", "Programming challenges", "Robot demonstrations", "Holiday showcase"],
  },
  {
    title: "Holiday Camp - Grades K-5 (Full Days)",
    description: "Design, build and program your own robot AND make a custom 3D printed holiday gift.",
    gradeLevel: "K - 5th Grade",
    dates: "Multiple sessions available",
    time: "Full days (extended hours)",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "3d-printing", "full-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: false },
    ],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Robot design", "3D modeling", "Programming", "Gift design", "Manufacturing"],
    projects: ["Custom robot build", "3D printed holiday gift", "Programming projects", "Holiday presentation"],
  },
  {
    title: "Holiday Camp - Grades 6-12 (Half Days)",
    description: "Advanced robotics camp where students design, build and program their own robot.",
    gradeLevel: "6th - 12th Grade",
    dates: "Multiple sessions available",
    time: "Morning 9am-12pm OR Afternoon 1pm-4pm",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "advanced", "half-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Advanced robotics", "Complex programming", "Engineering design", "System integration"],
    projects: ["Sophisticated robot build", "Advanced programming", "Engineering challenges", "Technical presentation"],
  },
  {
    title: "Holiday Camp - Grades 6-12 (Full Days)",
    description: "Comprehensive camp combining advanced robotics with 3D printing to create custom holiday gifts.",
    gradeLevel: "6th - 12th Grade",
    dates: "Multiple sessions available",
    time: "Full days (extended hours)",
    category: "Holiday Camp",
    tags: ["holiday", "robotics", "3d-printing", "advanced", "full-day"],
    sessions: [
      { name: "Session 1", dates: "Dec 26-28", available: true },
      { name: "Session 2", dates: "Dec 30, Jan 2-3", available: true },
      { name: "Session 3", dates: "February 20-22", available: true },
      { name: "Session 4", dates: "April 17-19 or 18-20", available: true },
    ],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Advanced robotics", "3D CAD design", "Manufacturing", "Programming", "Project management"],
    projects: ["Complex robot system", "Custom 3D printed gift", "Advanced programming", "Engineering portfolio"],
  },
]

export const fallCourses = [
  {
    title: "RBT001 - Robotics 100 (Grades K-3)",
    description: "Introductory VEX IQ robotics for youngest beginners with project-based learning.",
    gradeLevel: "K - 3rd Grade",
    dates: "10 sessions - Fall 2024",
    time: "Tuesday 3:00pm-4:00pm OR Sunday 9:00am-10:00am",
    category: "Beginner Robotics",
    courseCode: "RBT001",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "young-learners"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["VEX IQ basics", "Simple construction", "Basic programming", "Following instructions"],
    projects: ["Basic robot builds", "Simple movements", "Sensor exploration", "Creative designs"],
  },
  {
    title: "RBT001 - Robotics 100 (Grades 4-6)",
    description: "Introductory VEX IQ robotics with more complex projects for elementary students.",
    gradeLevel: "4th - 6th Grade",
    dates: "10 sessions - Fall 2024",
    time: "Tuesday 4:00pm-5:30pm OR Saturday 12:00pm-1:30pm",
    category: "Beginner Robotics",
    courseCode: "RBT001",
    color: "Light Blue",
    tags: ["robotics", "beginner", "vex-iq", "elementary"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["VEX IQ construction", "Programming logic", "Problem solving", "Design thinking"],
    projects: ["Moving robots", "Sensor-based robots", "Programming challenges", "Team projects"],
  },
  {
    title: "RBT001 - Robotics 100 (Grades 6-8)",
    description: "Advanced VEX IQ robotics for middle school students with complex mechanisms.",
    gradeLevel: "6th - 8th Grade",
    dates: "10 sessions - Fall 2024",
    time: "Saturday 6:00pm-7:00pm",
    category: "Intermediate Robotics",
    courseCode: "RBT001",
    color: "Light Blue",
    tags: ["robotics", "intermediate", "vex-iq", "middle-school"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Advanced VEX IQ", "Complex programming", "Mechanism design", "Competition prep"],
    projects: ["Competition-style robots", "Advanced mechanisms", "Autonomous programming", "Design challenges"],
  },
  {
    title: "RBT002 - Robotics 200 (Grades 6-8)",
    description: "Introduction to VEX robotics with gear ratios, torque, speed, and leverage concepts.",
    gradeLevel: "6th - 8th Grade",
    dates: "10 sessions - Fall 2024",
    time: "Tuesday 6:00pm-7:30pm",
    category: "Advanced Robotics",
    courseCode: "RBT002",
    color: "Red",
    tags: ["robotics", "advanced", "vex", "engineering"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["VEX construction", "Gear ratios", "Torque concepts", "Speed calculations", "Leverage principles"],
    projects: ["Basic VEX robot", "Gear demonstrations", "Mechanical advantage projects", "Engineering challenges"],
  },
  {
    title: "RBT002 - Robotics 200 (Grades 8-12)",
    description: "Advanced VEX robotics covering complex engineering concepts for high school students.",
    gradeLevel: "8th - 12th Grade",
    dates: "10 sessions - Fall 2024",
    time: "Tuesday 7:30pm-9:00pm OR Saturday 7:30pm-9:00pm OR Sunday 10:30am-12:00pm",
    category: "Advanced Robotics",
    courseCode: "RBT002",
    color: "Red",
    tags: ["robotics", "advanced", "vex", "high-school", "engineering"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Advanced VEX systems", "Engineering principles", "Complex programming", "Competition design"],
    projects: ["Competition robot", "Advanced mechanisms", "Engineering analysis", "Performance optimization"],
  },
]

export const summerCourses = [
  {
    title: "VEX V5 Competition Bootcamp",
    description: "8-week intensive bootcamp for competition team preparation.",
    gradeLevel: "6th - 12th Grade",
    dates: "Jun 30 - Aug 24, 2025",
    time: "Tue/Thu/Fri Sessions",
    category: "Competition Bootcamp",
    tags: ["competition", "bootcamp", "vex-v5", "intensive"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["V5 programming", "Competition design", "Leadership", "Public speaking"],
    projects: ["Competition robot", "Autonomous routines", "Strategy playbook", "Tournament prep"],
  },
  {
    title: "VEX IQ Competition Bootcamp",
    description: "8-week bootcamp for younger students interested in competition teams.",
    gradeLevel: "K - 7th Grade",
    dates: "Jun 30 - Aug 24, 2025",
    time: "Tue/Thu/Sat Sessions",
    category: "Competition Bootcamp",
    tags: ["competition", "bootcamp", "vex-iq", "intensive"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["IQ programming", "Mechanical design", "Teamwork", "Presentation"],
    projects: ["IQ robot", "Autonomous solutions", "Design journal", "Tournament participation"],
  },
  {
    title: "Weekly STEM Camps",
    description: "Week-long camps covering robotics, 3D printing, laser cutting, and more.",
    gradeLevel: "K - 12th Grade",
    dates: "Jun 30 - Aug 22, 2025",
    time: "Mon-Fri 9AM-4PM",
    category: "STEM Camp",
    tags: ["stem", "camp", "3d-printing", "fabrication"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["3D modeling", "Laser cutting", "Programming", "Research methods"],
    projects: ["3D printed parts", "Laser assemblies", "Research presentation", "Innovation projects"],
  },
  {
    title: "Weekend Camps - Mini Battle Bots",
    description: "Design and build your own mini battle bot to take home.",
    gradeLevel: "4th - 12th Grade",
    dates: "Jul 12-13, 2025",
    time: "Sat/Sun 9AM-3PM",
    category: "Weekend Camp",
    tags: ["weekend", "battlebots", "engineering"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Combat design", "Electronics", "Safety protocols", "Strategy"],
    projects: ["Battle bot design", "Control system", "Tournament participation", "Take-home robot"],
  },
  {
    title: "Weekend Camps - Electronics",
    description: "Explore electronics fundamentals and create projects to take home.",
    gradeLevel: "4th - 12th Grade",
    dates: "Jul 19-20, 2025",
    time: "Sat/Sun 9AM-3PM",
    category: "Weekend Camp",
    tags: ["weekend", "electronics", "circuits"],
    soldOut: true,
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Circuit design", "Soldering", "Component ID", "Testing"],
    projects: ["LED controller", "Sound display", "Temperature monitor", "Electronic badge"],
  },
  {
    title: "Weekend Camps - Game Design",
    description: "Learn game development and create your own games.",
    gradeLevel: "4th - 12th Grade",
    dates: "Jul 26-27, 2025",
    time: "Sat/Sun 9AM-3PM",
    category: "Weekend Camp",
    tags: ["weekend", "game-design", "programming"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Game design", "Programming", "UI design", "Animation"],
    projects: ["2D platform game", "Puzzle game", "Character animation", "Game portfolio"],
  },
  {
    title: "Weekend Camps - Drones",
    description: "Build and program your own drone with flight control systems.",
    gradeLevel: "4th - 12th Grade",
    dates: "Aug 9-10, 2025",
    time: "Sat/Sun 9AM-3PM",
    category: "Weekend Camp",
    tags: ["weekend", "drones", "flight", "programming"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Aerodynamics", "Drone assembly", "Flight programming", "Safety"],
    projects: ["Custom quadcopter", "Flight patterns", "Obstacle navigation", "Take-home drone"],
  },
  {
    title: "Weekend Camps - Puzzle Making",
    description: "Design and create custom puzzles using engineering principles.",
    gradeLevel: "4th - 12th Grade",
    dates: "Aug 16-17, 2025",
    time: "Sat/Sun 9AM-3PM",
    category: "Weekend Camp",
    notAvailable: true,
    tags: ["weekend", "puzzles", "design", "3d-printing"],
    imageUrl: "/gallery/placeholder.webp?height=200&width=300",
    skills: ["Puzzle design", "3D modeling", "Manufacturing", "UX design"],
    projects: ["Mechanical puzzle", "3D printed components", "Wooden puzzle", "Electronic integration"],
  },
]
